'use client';

import { useState, useRef, useEffect, useCallback } from 'react';
import { 
  Send, Sparkles, Code2, Eye, FolderOpen, Plus, FileCode, Folder,
  ChevronRight, X, Play, Download, Upload, Settings,
  PanelLeftClose, PanelLeft,
  Loader2, Check, Copy, Trash2, RefreshCw, GitBranch, Cloud,
  Zap, Layers, FileText, Globe, Terminal, ExternalLink
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { toast } from 'sonner';
import { cn } from '@/lib/utils';

// Types
interface FileNode {
  id: string;
  name: string;
  path: string;
  type: 'file' | 'folder';
  content?: string;
  language?: string;
  children?: FileNode[];
}

interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
  codeBlocks?: CodeBlock[];
}

interface CodeBlock {
  language: string;
  code: string;
  filename?: string;
}

interface Project {
  id: string;
  name: string;
  framework: 'nextjs' | 'react' | 'vue' | 'html';
  files: FileNode[];
  createdAt: Date;
}

// Default project template
const defaultProject: Project = {
  id: 'default',
  name: 'My Project',
  framework: 'nextjs',
  files: [
    { id: '1', name: 'src', path: '/src', type: 'folder', children: [
      { id: '2', name: 'app', path: '/src/app', type: 'folder', children: [
        { id: '3', name: 'page.tsx', path: '/src/app/page.tsx', type: 'file', language: 'typescript', content: `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <h1 className="text-4xl font-bold">Hello World!</h1>
      <p className="mt-4 text-gray-500">Start editing to see changes</p>
    </main>
  );
}` },
        { id: '4', name: 'layout.tsx', path: '/src/app/layout.tsx', type: 'file', language: 'typescript', content: `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by December AI",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}` },
        { id: '5', name: 'globals.css', path: '/src/app/globals.css', type: 'file', language: 'css', content: `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --background: #ffffff;
  --foreground: #171717;
}

body {
  color: var(--foreground);
  background: var(--background);
}` },
      ]},
      { id: '6', name: 'components', path: '/src/components', type: 'folder', children: [] },
    ]},
    { id: '7', name: 'package.json', path: '/package.json', type: 'file', language: 'json', content: `{
  "name": "my-project",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "^15.0.0",
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  }
}` },
    { id: '8', name: 'next.config.ts', path: '/next.config.ts', type: 'file', language: 'typescript', content: `import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  reactStrictMode: true,
};

export default nextConfig;` },
  ],
  createdAt: new Date(),
};

export default function DecemberStudio() {
  // State
  const [project, setProject] = useState<Project>(defaultProject);
  const [activeFile, setActiveFile] = useState<FileNode | null>(null);
  const [openFiles, setOpenFiles] = useState<FileNode[]>([]);
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [inputMessage, setInputMessage] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [leftPanelOpen, setLeftPanelOpen] = useState(true);
  const [rightPanelOpen, setRightPanelOpen] = useState(true);
  const [activeTab, setActiveTab] = useState<'code' | 'preview'>('code');
  const [previewCode, setPreviewCode] = useState('');
  const [expandedFolders, setExpandedFolders] = useState<Set<string>>(new Set(['/src', '/src/app']));
  
  const chatEndRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Scroll to bottom of chat
  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  // Open first file on load
  useEffect(() => {
    const firstFile = findFirstFile(project.files);
    if (firstFile) {
      setActiveFile(firstFile);
      setOpenFiles([firstFile]);
    }
  }, []);

  // Find first file in tree
  const findFirstFile = (nodes: FileNode[]): FileNode | null => {
    for (const node of nodes) {
      if (node.type === 'file') return node;
      if (node.children) {
        const found = findFirstFile(node.children);
        if (found) return found;
      }
    }
    return null;
  };

  // Find file by path
  const findFileByPath = useCallback((nodes: FileNode[], path: string): FileNode | null => {
    for (const node of nodes) {
      if (node.path === path) return node;
      if (node.children) {
        const found = findFileByPath(node.children, path);
        if (found) return found;
      }
    }
    return null;
  }, []);

  // Update file content
  const updateFileContent = useCallback((path: string, content: string) => {
    const updateNode = (nodes: FileNode[]): FileNode[] => {
      return nodes.map(node => {
        if (node.path === path) {
          return { ...node, content };
        }
        if (node.children) {
          return { ...node, children: updateNode(node.children) };
        }
        return node;
      });
    };
    
    setProject(prev => ({
      ...prev,
      files: updateNode(prev.files),
    }));
    
    setActiveFile(prev => prev?.path === path ? { ...prev, content } : prev);
    setOpenFiles(prev => prev.map(f => f.path === path ? { ...f, content } : f));
  }, []);

  // Open file in editor
  const openFile = useCallback((file: FileNode) => {
    if (file.type === 'file') {
      setActiveFile(file);
      if (!openFiles.find(f => f.path === file.path)) {
        setOpenFiles(prev => [...prev, file]);
      }
    } else {
      // Toggle folder
      setExpandedFolders(prev => {
        const next = new Set(prev);
        if (next.has(file.path)) {
          next.delete(file.path);
        } else {
          next.add(file.path);
        }
        return next;
      });
    }
  }, [openFiles]);

  // Close file
  const closeFile = useCallback((file: FileNode) => {
    setOpenFiles(prev => prev.filter(f => f.path !== file.path));
    if (activeFile?.path === file.path) {
      const remaining = openFiles.filter(f => f.path !== file.path);
      setActiveFile(remaining[remaining.length - 1] || null);
    }
  }, [activeFile, openFiles]);

  // Send message to AI
  const sendMessage = async () => {
    if (!inputMessage.trim() || isLoading) return;

    const userMessage: ChatMessage = {
      id: Date.now().toString(),
      role: 'user',
      content: inputMessage,
      timestamp: new Date(),
    };

    setMessages(prev => [...prev, userMessage]);
    setInputMessage('');
    setIsLoading(true);

    try {
      const response = await fetch('/api/ai/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          message: inputMessage,
          projectContext: {
            name: project.name,
            framework: project.framework,
            currentFile: activeFile?.path,
            fileContent: activeFile?.content,
          },
          history: messages.slice(-10).map(m => ({ role: m.role, content: m.content })),
        }),
      });

      const data = await response.json();
      
      const codeBlocks = parseCodeBlocks(data.response);
      
      const assistantMessage: ChatMessage = {
        id: (Date.now() + 1).toString(),
        role: 'assistant',
        content: data.response,
        timestamp: new Date(),
        codeBlocks,
      };

      setMessages(prev => [...prev, assistantMessage]);

      if (codeBlocks.length > 0 && codeBlocks[0].filename) {
        const block = codeBlocks[0];
        updateFileContent(block.filename || activeFile?.path || '', block.code);
      }
    } catch (error) {
      console.error('Error sending message:', error);
      toast.error('Failed to get AI response');
      
      setMessages(prev => [...prev, {
        id: (Date.now() + 1).toString(),
        role: 'assistant',
        content: 'Sorry, I encountered an error. Please try again.',
        timestamp: new Date(),
      }]);
    } finally {
      setIsLoading(false);
    }
  };

  // Parse code blocks from markdown
  const parseCodeBlocks = (text: string): CodeBlock[] => {
    const regex = /```(\w+)?(?:\s+([^\n]+))?\n([\s\S]*?)```/g;
    const blocks: CodeBlock[] = [];
    let match;
    
    while ((match = regex.exec(text)) !== null) {
      blocks.push({
        language: match[1] || 'text',
        filename: match[2]?.trim(),
        code: match[3].trim(),
      });
    }
    
    return blocks;
  };

  // Apply code block
  const applyCodeBlock = (block: CodeBlock) => {
    if (block.filename) {
      updateFileContent(block.filename, block.code);
      toast.success(`Updated ${block.filename}`);
    } else if (activeFile) {
      updateFileContent(activeFile.path, block.code);
      toast.success('Code applied!');
    }
  };

  // Generate preview
  const generatePreview = () => {
    setActiveTab('preview');
    const pageFile = findFileByPath(project.files, '/src/app/page.tsx');
    setPreviewCode(`
<!DOCTYPE html>
<html>
<head>
  <title>Preview</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-white text-gray-900">
  <div class="p-8">
    <h1 class="text-2xl font-bold">Preview</h1>
    <p class="mt-4 text-gray-600">Live preview of your project</p>
  </div>
</body>
</html>`);
  };

  // Create new file
  const createNewFile = () => {
    const name = prompt('Enter file name:');
    if (!name) return;
    
    const newFile: FileNode = {
      id: Date.now().toString(),
      name,
      path: `/${name}`,
      type: 'file',
      content: '',
      language: name.endsWith('.tsx') ? 'typescript' : name.endsWith('.css') ? 'css' : 'text',
    };
    
    setProject(prev => ({
      ...prev,
      files: [...prev.files, newFile],
    }));
    
    openFile(newFile);
    toast.success(`Created ${name}`);
  };

  // Render file tree
  const renderFileTree = (nodes: FileNode[], level = 0): React.ReactNode => {
    return nodes
      .sort((a, b) => {
        if (a.type !== b.type) return a.type === 'folder' ? -1 : 1;
        return a.name.localeCompare(b.name);
      })
      .map(node => {
        const isExpanded = expandedFolders.has(node.path);
        const isFolder = node.type === 'folder';
        
        return (
          <div key={node.id}>
            <button
              onClick={() => openFile(node)}
              className={cn(
                "w-full flex items-center gap-1.5 px-2 py-1 text-sm hover:bg-[#1e1e1e] rounded transition-colors",
                activeFile?.path === node.path && "bg-[#1e3a5f] text-white"
              )}
              style={{ paddingLeft: `${level * 12 + 8}px` }}
            >
              {isFolder ? (
                <>
                  <ChevronRight className={cn("w-3 h-3 text-gray-500 transition-transform", isExpanded && "rotate-90")} />
                  <Folder className="w-4 h-4 text-yellow-500" />
                </>
              ) : (
                <>
                  <span className="w-3" />
                  <FileCode className="w-4 h-4 text-blue-400" />
                </>
              )}
              <span className="truncate">{node.name}</span>
            </button>
            {isFolder && node.children && isExpanded && (
              renderFileTree(node.children, level + 1)
            )}
          </div>
        );
      });
  };

  // Render code block in chat
  const renderCodeBlock = (block: CodeBlock, index: number) => (
    <div key={index} className="my-3 rounded-lg overflow-hidden border border-[#333]">
      <div className="flex items-center justify-between bg-[#1a1a1a] px-3 py-2">
        <span className="text-xs text-gray-400">
          {block.language} {block.filename && `• ${block.filename}`}
        </span>
        <div className="flex items-center gap-1">
          <Button
            size="sm"
            variant="ghost"
            className="h-6 px-2 text-xs"
            onClick={() => {
              navigator.clipboard.writeText(block.code);
              toast.success('Copied!');
            }}
          >
            <Copy className="w-3 h-3 mr-1" /> Copy
          </Button>
          <Button
            size="sm"
            variant="ghost"
            className="h-6 px-2 text-xs text-green-400 hover:text-green-300"
            onClick={() => applyCodeBlock(block)}
          >
            <Check className="w-3 h-3 mr-1" /> Apply
          </Button>
        </div>
      </div>
      <pre className="p-3 bg-[#0d0d0d] overflow-x-auto text-sm">
        <code>{block.code}</code>
      </pre>
    </div>
  );

  // Render message content with code blocks
  const renderMessageContent = (message: ChatMessage) => {
    const parts = message.content.split(/(```[\s\S]*?```)/g);
    
    return parts.map((part, i) => {
      if (part.startsWith('```')) {
        const match = part.match(/```(\w+)?(?:\s+([^\n]+))?\n([\s\S]*?)```/);
        if (match) {
          const block: CodeBlock = {
            language: match[1] || 'text',
            filename: match[2]?.trim(),
            code: match[3].trim(),
          };
          return renderCodeBlock(block, i);
        }
      }
      return <span key={i} className="whitespace-pre-wrap">{part}</span>;
    });
  };

  return (
    <div className="h-screen flex flex-col bg-[#0a0a0a] text-white overflow-hidden">
      {/* Header */}
      <header className="h-12 bg-[#0d0d0d] border-b border-[#222] flex items-center justify-between px-4 shrink-0">
        <div className="flex items-center gap-3">
          <button
            onClick={() => setLeftPanelOpen(!leftPanelOpen)}
            className="p-1.5 hover:bg-[#222] rounded transition"
          >
            {leftPanelOpen ? <PanelLeftClose className="w-4 h-4" /> : <PanelLeft className="w-4 h-4" />}
          </button>
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-500 to-purple-600 flex items-center justify-center">
              <Sparkles className="w-4 h-4" />
            </div>
            <div>
              <h1 className="font-semibold text-sm">December Studio</h1>
              <p className="text-[10px] text-gray-500">AI-Powered Web Builder</p>
            </div>
          </div>
        </div>
        
        <div className="flex items-center gap-2">
          <span className="text-xs text-gray-500 px-3 py-1 bg-[#1a1a1a] rounded-full">
            {project.name}
          </span>
          <Button size="sm" variant="ghost" className="text-xs">
            <GitBranch className="w-3 h-3 mr-1" /> main
          </Button>
        </div>
        
        <div className="flex items-center gap-2">
          <Button size="sm" variant="ghost" onClick={generatePreview}>
            <Eye className="w-4 h-4 mr-1" /> Preview
          </Button>
          <Button size="sm" className="bg-green-600 hover:bg-green-700">
            <Cloud className="w-4 h-4 mr-1" /> Deploy
          </Button>
        </div>
      </header>

      {/* Main Content */}
      <div className="flex-1 flex overflow-hidden">
        {/* Left Panel - File Explorer */}
        {leftPanelOpen && (
          <aside className="w-60 bg-[#0d0d0d] border-r border-[#222] flex flex-col shrink-0">
            <div className="h-10 px-3 flex items-center justify-between border-b border-[#222]">
              <span className="text-xs font-semibold text-gray-400 uppercase">Explorer</span>
              <button onClick={createNewFile} className="p-1 hover:bg-[#222] rounded">
                <Plus className="w-4 h-4 text-gray-400" />
              </button>
            </div>
            <ScrollArea className="flex-1">
              <div className="py-2">
                {renderFileTree(project.files)}
              </div>
            </ScrollArea>
          </aside>
        )}

        {/* Center - Code Editor */}
        <main className="flex-1 flex flex-col overflow-hidden">
          {/* Tabs */}
          <div className="h-10 bg-[#0d0d0d] border-b border-[#222] flex items-center shrink-0 overflow-x-auto">
            {openFiles.map((file) => (
              <button
                key={file.id}
                onClick={() => setActiveFile(file)}
                className={cn(
                  "flex items-center gap-2 px-3 py-2 text-sm border-r border-[#222] transition min-w-0",
                  activeFile?.path === file.path
                    ? "bg-[#0a0a0a] text-white"
                    : "text-gray-400 hover:bg-[#111]"
                )}
              >
                <FileCode className="w-4 h-4 text-blue-400 shrink-0" />
                <span className="truncate">{file.name}</span>
                <button
                  onClick={(e) => { e.stopPropagation(); closeFile(file); }}
                  className="hover:bg-[#333] rounded p-0.5"
                >
                  <X className="w-3 h-3" />
                </button>
              </button>
            ))}
          </div>

          {/* Editor Area */}
          <div className="flex-1 flex overflow-hidden">
            {/* Code Editor */}
            <div className={cn("flex-1 flex flex-col overflow-hidden", activeTab === 'preview' && 'hidden')}>
              {activeFile ? (
                <textarea
                  value={activeFile.content || ''}
                  onChange={(e) => updateFileContent(activeFile.path, e.target.value)}
                  className="flex-1 bg-[#0a0a0a] p-4 font-mono text-sm resize-none focus:outline-none text-gray-200"
                  spellCheck={false}
                />
              ) : (
                <div className="flex-1 flex items-center justify-center text-gray-500">
                  <div className="text-center">
                    <Code2 className="w-16 h-16 mx-auto mb-4 opacity-50" />
                    <p>Select a file to start editing</p>
                  </div>
                </div>
              )}
            </div>

            {/* Preview */}
            {activeTab === 'preview' && (
              <div className="flex-1 bg-white">
                <iframe
                  srcDoc={previewCode}
                  className="w-full h-full border-0"
                  title="Preview"
                />
              </div>
            )}
          </div>

          {/* Tab Switcher */}
          <div className="h-8 bg-[#0d0d0d] border-t border-[#222] flex items-center px-2 shrink-0">
            <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as 'code' | 'preview')}>
              <TabsList className="h-6">
                <TabsTrigger value="code" className="text-xs h-6 px-2">
                  <Code2 className="w-3 h-3 mr-1" /> Code
                </TabsTrigger>
                <TabsTrigger value="preview" className="text-xs h-6 px-2">
                  <Eye className="w-3 h-3 mr-1" /> Preview
                </TabsTrigger>
              </TabsList>
            </Tabs>
          </div>
        </main>

        {/* Right Panel - AI Chat */}
        {rightPanelOpen && (
          <aside className="w-96 bg-[#0d0d0d] border-l border-[#222] flex flex-col shrink-0">
            <div className="h-10 px-3 flex items-center justify-between border-b border-[#222]">
              <div className="flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-blue-400" />
                <span className="text-sm font-medium">AI Assistant</span>
              </div>
              <button
                onClick={() => setRightPanelOpen(false)}
                className="p-1 hover:bg-[#222] rounded"
              >
                <X className="w-4 h-4 text-gray-400" />
              </button>
            </div>

            {/* Chat Messages */}
            <ScrollArea className="flex-1 p-4">
              {messages.length === 0 ? (
                <div className="text-center text-gray-500 py-8">
                  <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-gradient-to-br from-blue-500 to-purple-600 flex items-center justify-center">
                    <Sparkles className="w-8 h-8" />
                  </div>
                  <h3 className="font-medium mb-2 text-white">Hi, I&apos;m your AI assistant!</h3>
                  <p className="text-sm mb-4">I can help you build web applications.</p>
                  <div className="grid grid-cols-2 gap-2 text-xs">
                    {[
                      'Create a landing page',
                      'Build a dashboard',
                      'Add a contact form',
                      'Make it responsive',
                    ].map((suggestion) => (
                      <button
                        key={suggestion}
                        onClick={() => setInputMessage(suggestion)}
                        className="p-2 bg-[#1a1a1a] border border-[#333] rounded hover:border-blue-500 transition text-left"
                      >
                        {suggestion}
                      </button>
                    ))}
                  </div>
                </div>
              ) : (
                <div className="space-y-4">
                  {messages.map((message) => (
                    <div
                      key={message.id}
                      className={cn(
                        "p-3 rounded-lg",
                        message.role === 'user'
                          ? "bg-blue-600/20 border border-blue-600/30"
                          : "bg-[#1a1a1a] border border-[#333]"
                      )}
                    >
                      <div className="text-sm">
                        {renderMessageContent(message)}
                      </div>
                      <div className="text-[10px] text-gray-500 mt-2">
                        {message.timestamp.toLocaleTimeString()}
                      </div>
                    </div>
                  ))}
                  <div ref={chatEndRef} />
                </div>
              )}
            </ScrollArea>

            {/* Chat Input */}
            <div className="p-3 border-t border-[#222]">
              <div className="flex gap-2">
                <Textarea
                  ref={textareaRef}
                  value={inputMessage}
                  onChange={(e) => setInputMessage(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' && !e.shiftKey) {
                      e.preventDefault();
                      sendMessage();
                    }
                  }}
                  placeholder="Describe what you want to build..."
                  className="min-h-[60px] max-h-[120px] bg-[#1a1a1a] border-[#333] resize-none text-sm"
                  disabled={isLoading}
                />
                <Button
                  onClick={sendMessage}
                  disabled={!inputMessage.trim() || isLoading}
                  className="bg-blue-600 hover:bg-blue-700 shrink-0"
                >
                  {isLoading ? (
                    <Loader2 className="w-4 h-4 animate-spin" />
                  ) : (
                    <Send className="w-4 h-4" />
                  )}
                </Button>
              </div>
            </div>
          </aside>
        )}

        {/* Floating AI Button */}
        {!rightPanelOpen && (
          <button
            onClick={() => setRightPanelOpen(true)}
            className="fixed bottom-4 right-4 p-4 bg-gradient-to-r from-blue-600 to-purple-600 rounded-full shadow-lg hover:scale-110 transition-transform z-50"
          >
            <Sparkles className="w-5 h-5" />
          </button>
        )}
      </div>
    </div>
  );
}
